version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONDODB_DATABASE: example
    ports:
        - "27017:27017"
    volumes:
        - ./data/db:/data/db
        - ./data/configdb:/data/configdb
        - ./data/dump:/data/dump
